language: php
sudo: false
dist: trusty
php:
  - 7.1
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"
before_script:
  - composer self-update
  - composer update $DEPENDENCIES
script:
  - ./vendor/bin/phpunit
